# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9b79c522e5a7ed0ca39e57b875e7d6b230828d6f4ca93439613815ef5d3dd85fd185fd81557558796c3e4dc8781eeddc50e004c4a964475d79b4fa4b480fdf

test:
  secret_key_base: 631b299e3e0260fe847b9d57410ea6323c93fd89e1c8a71cde8de397470cb5c87821e6d3b606cc257d2acf7c833bf3acf1d59fd0141d7e8f8358e5bca8a2e42e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
